name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: gcc Calci.c -o Calci.exe
    - name: make
      run: make
    - name: Run
      run: .\Calci.exe
