name: Linux C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install make
    - name: Make
      run: gcc hello.c -o hello.exe
    - name: Run
      run: ./hello.exe
